lsi: false
safe: true
source: .
incremental: false
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge

title: Byteshinobi
description: Personal website and blog
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
markdown: kramdown
theme: null
plugins:
- jekyll-feed
- jekyll-seo-tag

# Exclude from processing
exclude:
- Gemfile
- Gemfile.lock
- node_modules
- vendor
- .gitignore
